In [1]:
import numpy as np

In [2]:
#create (x, y) data
xy = np.random.random((10000, 2))

In [3]:
#separate x and y
x1 = xy[:,0]
y1 = xy[:,1]
#dupicate x y, reshape them
x2 = x1.reshape((10000, 1))
y2 = y1.reshape((10000, 1))

In [4]:
#calucate r
r = ((x1-x2)**2 + (y1-y2)**2)**0.5

In [5]:
#the minimnum r is 0, which is trivial.
#We need to find the 2nd closest one
r[r == 0] = 9999 # mask r=0 points
r.min(axis=1) # this is the closest distance rather than 0 

array([0.00444551, 0.00142183, 0.00627402, ..., 0.00818233, 0.01427322,
       0.00402247])

In [6]:
#find the indices of closet points
#the first element in array1 match first element in array2
np.where(r == r.min(axis =1).reshape(10000, 1))

(array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64),
 array([1619,  944,  615, ..., 7646, 1555, 7291], dtype=int64))